apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: kaniko
build:
  artifacts:
    - image: docker-registry.csikoste.com/kaniko-executor-arm
      kaniko: &KANIKO
        buildArgs: &BUILD_ARGS
          GOARCH: arm
          KANIKO_VERSION: v1.2.0
        cache:
          repo: docker-registry.csikoste.com/cache
          hostPath: /cache/
        image: matefarkas/kaniko-executor:v1.2.0-arm
        volumeMounts:
          - name: persistent-cache
            mountpath: /persistent-cache/
            readonly: true
    - image: docker-registry.csikoste.com/kaniko-warmer-arm
      kaniko:
        <<: *KANIKO
        buildArgs:
          <<: *BUILD_ARGS
          COMPONENT: warmer
  cluster:
    dockerConfig:
      secretName: docker-registry-kanikosecret
    volumes:
      - name: persistent-cache
        volumesource:
          persistentvolumeclaim:
            claimname: kaniko-cache

profiles:
  - name: dev
    patches:
      - op: replace
        path: /build
        value:
          artifacts:
            - image: docker-registry.csikoste.com/kaniko-executor
            - image: docker-registry.csikoste.com/kaniko-warmer
              docker:
                buildArgs:
                  COMPONENT: warmer
